name: backend
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  lints: ^1.0.0
dependencies: 
  dart_jsonwebtoken: ^2.4.1
  shelf: ^1.2.0
  shelf_router: ^1.1.2
